service: flashcards-api
app: flashcards
org: chrischapman900

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  environment:
    DB_CONNECTION_STRING: ${file(./.env.yaml):${self:provider.stage}.DB_CONNECTION_STRING}

package:
  exclude:
    - docs/**

functions:
  getWords:
    handler: controllers/word.getWords
    events:
      - http:
          path: words
          method: get
  getWord:
    handler: controllers/word.getWord
    events:
      - http:
          path: words/{wordId}
          method: get

plugins:
  - serverless-offline
