service: flashcards-api
app: flashcards
org: chrischapman900

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  environment:
    PGUSER: ${file(./.env.yaml):${self:provider.stage}.POSTGRES.USER}
    PGHOST: ${file(./.env.yaml):${self:provider.stage}.POSTGRES.HOST}
    PGDATABASE: ${file(./.env.yaml):${self:provider.stage}.POSTGRES.DATABASE}
    PGPORT: ${file(./.env.yaml):${self:provider.stage}.POSTGRES.PORT}
    CHRIS_USER_ID: ${file(./.env.yaml):${self:provider.stage}.CHRIS_USER_ID}

package:
  exclude:
    - docs/**

functions:
  getWords:
    handler: controllers/word.getWords
    events:
      - http:
          path: words
          method: get
  getWord:
    handler: controllers/word.getWord
    events:
      - http:
          path: words/{wordId}
          method: get
  updateWordConfidence:
    handler: controllers/word.updateWordConfidence
    events:
      - http:
          path: words/{wordId}
          method: put


plugins:
  - serverless-offline
