openapi: "3.0.0"
info:
  version: 2.0.1
  title: Flashcards API
  description: An API that allows user to do language-learning flashcards
  contact:
    name: Chris Chapman
    email: chrischapman900@gmail.com
    url: http://chrischapman.co
paths:
  /words:
    get:
      summary: List words
      description: List all word, with optional search by part of speech
      operationId: listWords
      tags:
        - Words
      parameters:
        - name: partOfSpeech
          in: query
          description: What type of partOfSpeech to return
          required: false
          schema:
            type: string
        - name: sessionConfidenceMax
          in: query
          description: Maximum value of the session confidence allowed (to filter out known words)
          required: false
          schema:
            type: integer
        - name: overallConfidenceMax
          in: query
          description: Maximum value of the overall confidence allowed (to filter out known words)
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: A paged array of Words
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Word"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /words/{wordId}:
    parameters:
      - name: wordId
        in: path
        required: true
        description: The id of the word
        schema:
          type: integer
    get:
      summary: Get word
      operationId: getWord
      tags:
        - Words
      responses:
        '200':
          description: The requested Word
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Word"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      summary: Update Word Confidence
      operationId: updateWordConfidence
      tags:
        - Words
      requestBody:
        description: The confidence to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfidenceRequestPayload'
      responses:
        '200':
          description: The requested Word
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Word'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:

    Word:
      required:
        - id
        - hebrew
        - english
        - count
        - partOfSpeech
      properties:
        id:
          type: string
          example: 1
        hebrew:
          type: string
          example: נתן
        english:
          type: string
          example: to give, put, set
        count:
          type: integer
          example: 2140
        partOfSpeech:
          type: string
          example: verb
        sessionConfidence:
          type: integer
          example: 3
          maximum: 5
        overallConfidence:
          type: integer
          example: 3
          maximum: 5

    User:
      required:
        - id
        - name
      properties:
        id:
          type: string
          example: 42
        name:
          type: string
          example: Chris

    ConfidenceRequestPayload:
      required:
        - word
        - mode
        - overallResults
      properties:
        wordId:
          type: string
          example: 5a9439a24e443d2b5c9d7aaf
        userId:
          type: string
          example: 5a9439a24e443d2b5c9d7aaf
        value:
          description: On a scale from 1-5 on how confident about a word
          type: integer
          example: 4

    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string